Image disappears when screen width under 800
jprofessionals/my-page pull request #521
Opened 2023-07-18 12:59 UTC by ulrikror99

2023-07-18 13:10 UTC, brehen commented on my-page-app/src/components/hyttebooking/Hyttebooking.tsx
> +            <Image
Prøv dette istedet:

```suggestion
            <Image
              class="hidden md:block"
```

2023-07-18 13:11 UTC, brehen requested changes
Se kommentaren. Dette kan løses enklere med responsive prefix fra tailwind :)

Endre fra `md` til skjermstørrelse som passer bedre (sm/md/lg/xl)

2023-07-18 13:21 UTC, ulrikror99 commented on my-page-app/src/components/hyttebooking/Hyttebooking.tsx
> +            <Image
Takk! Skal fikse det nå :)

2023-07-19 07:25 UTC, brehen approved these changes
Fjern useEffect importen, så er det bare å merge

2023-07-19 07:25 UTC, brehen commented on my-page-app/src/components/hyttebooking/Hyttebooking.tsx
> +import { useEffect, useState } from 'react'
Fjern useEffect her :)

2023-07-19 07:26 UTC, merged