Feature/bidra til min side
jprofessionals/my-page pull request #83
Opened 2022-10-05 08:13 UTC by TerjeJPro

Faktorert ut Budsjett fra hovedsiden og lagt inn ny side som beskriver hvordan man kan bidra til å videreutvikle "min side"

2022-10-05 08:50 UTC, rogerslaaen requested changes
- Package.json og package-lock.json på rot er vel ikke nødvendig?
- Når du flyttet Toast containeren fra App sluttet den å fungere - tenker den bør ligge så langt ut som mulig
- Tror ikke utlogging og logget-ut siden funker helt lenger
- Tror også loading ikke er helt topp lenger - du kan teste hvordan de ser ut om du setter breakpoints i api-et i getCurrentLoggedInUser og getBudgets (i api-controlleren
![image](https://user-images.githubusercontent.com/106536364/194018094-8c9630b8-4b34-4abc-b310-484585f68808.png)

2022-10-05 11:44 UTC, TerjeJPro commented
package filene, toast, og loading burde nå fungere. Utloggingssiden krever større refaktorering for å kunne navigere uten å være logget inn, så den kommer i egen commit

2022-10-05 12:30 UTC, rogerslaaen commented
Ser også at /budgets lastes litt mange ganger, tror i hvert fall de to siste kunne vært unngått
![image](https://user-images.githubusercontent.com/106536364/194060596-bf33a8d5-3594-4517-8a55-31c35bd7f422.png)

2022-10-06 09:10 UTC, TerjeJPro commented
Det gjenstår en siste liten ting. Spinneren med "Laster bruker" er ikke synlig mens brukerinfo hentes fra backend.

2022-10-06 10:17 UTC, rogerslaaen approved these changes

2022-10-06 10:18 UTC, merged